#!name= 4 in 1
#!desc= 模块插件重写合集
#!homepage=https://whatshub.top
#!author=ybnet
#!icon=https://whatshub.top/IMG/ybnet.png


# 给不喜欢收藏网址的朋友


[URL Rewrite]
# 浏览器google搜索模块 跳转到小火箭模块合集
^https?://www\.google\.com/search\?q=%E6%A8%A1%E5%9D%97.*$ https://whatshub.top/shadowrocket 302

# 浏览器google搜索插件 跳转到loon插件合集
^https?://www\.google\.com/search\?q=%E6%8F%92%E4%BB%B6.*$ https://whatshub.top/loon 302

# 浏览器google搜索重写 跳转到圈X重写合集
^https?://www\.google\.com/search\?q=%E9%87%8D%E5%86%99.*$ https://whatshub.top/quantumultx 302

# 浏览器google搜索sg 跳转到surge模块合集
^https?://www\.google\.com/search\?q=sg.*$ https://whatshub.top/surge 302

# 浏览器google搜索覆写 跳转到stash覆写合集   
^https?://www\.google\.com/search\?q=%E8%A6%86%E5%86%99.*$ https://whatshub.top/stash 302



[MITM]
hostname= %APPEND% whatshub.top,www.google.com